project: default
source:
  repoURL: https://github.com/mukhiddinov/agro.git
  targetRevision: main
  path: helm/agro
  helm:
    valueFiles:
      - values/catalog.yaml
destination:
  server: https://kubernetes.default.svc
  namespace: agro
syncPolicy:
  automated:
    prune: true
    selfHeal: true
