replicaCount: 2

image:
  repository: docker.io/mukhiddinov/agro-order-service
  tag: "latest"
  pullPolicy: Always

containerPort: 8080

service:
  type: ClusterIP
  port: 8080

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgres.db.svc.cluster.local:5432/orderdb
  - name: SPRING_DATASOURCE_USERNAME
    value: agro
  - name: SPRING_DATASOURCE_PASSWORD
    value: agro123
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: kafka.kafka.svc.cluster.local:9092
  - name: SHIPPING_BASE_URL
    value: http://shipping-service.default.svc.cluster.local:8089
  - name: INVENTORY_GRPC_ADDRESS
    value: inventory-service.default.svc.cluster.local:9091
  - name: PAYMENT_GRPC_ADDRESS
    value: payment-service.default.svc.cluster.local:9093

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
