replicaCount: 2

image:
  repository: docker.io/mukhiddinov/agro-payment-service
  tag: "latest"
  pullPolicy: Always

containerPort: 8087

service:
  type: ClusterIP
  port: 8087

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgres.db.svc.cluster.local:5432/paymentdb
  - name: SPRING_DATASOURCE_USERNAME
    value: agro
  - name: SPRING_DATASOURCE_PASSWORD
    value: agro123
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: kafka.kafka.svc.cluster.local:9092

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
