replicaCount: 2

image:
  repository: docker.io/mukhiddinov/agro-pricing-service
  tag: "latest"
  pullPolicy: Always

containerPort: 8084

service:
  type: ClusterIP
  port: 8084

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgres.db.svc.cluster.local:5432/pricingdb
  - name: SPRING_DATASOURCE_USERNAME
    value: agro
  - name: SPRING_DATASOURCE_PASSWORD
    value: agro123

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
