replicaCount: 1
nameOverride: ""
fullnameOverride: ""
image:
  repository: docker.io/mukhiddinov/checkout-service
  tag: "51b76464de3ab6613a623bbb43d986a5f0aba485"
  pullPolicy: Always
  registry: docker.io/mukhiddinov/checkout-service
containerPort: 8080
service:
  type: ClusterIP
  port: 8080
env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgres.db.svc.cluster.local:5432/agrodb
  - name: SPRING_DATASOURCE_USERNAME
    value: agro
  - name: SPRING_DATASOURCE_PASSWORD
    value: agro123
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: redpanda.kafka.svc.cluster.local:9093
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
