replicaCount: 1

image:
  repository: docker.io/mukhiddinov/agro-order-service
  tag: latest
  pullPolicy: Always

containerPort: 8080

service:
  type: ClusterIP
  port: 8080

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgres.db.svc.cluster.local:5432/agrodb
  - name: SPRING_DATASOURCE_USERNAME
    value: agro
  - name: SPRING_DATASOURCE_PASSWORD
    value: agro123
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: redpanda.kafka.svc.cluster.local:9093

