replicaCount: 1
nameOverride: ""
fullnameOverride: ""
image:
  registry: docker.io/mukhiddinov/agro-order-service
  tag: "acd638620423e147a418c2de19341b9af719f9b7"
containerPort: 8080
service:
  type: ClusterIP
  port: 8080
env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgres:5432/agrodb
  - name: SPRING_DATASOURCE_USERNAME
    value: agro
  - name: SPRING_DATASOURCE_PASSWORD
    value: agro123
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: redpanda.kafka.svc.cluster.local:9093
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
