apiVersion: v1
kind: Service
metadata:
  name: {{ include "agro.fullname" . }}
  labels:
    {{- include "agro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "agro.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
