replicaCount: 1
nameOverride: ""
fullnameOverride: ""
image:
  repository: docker.io/mukhiddinov/user-service
  tag: "e3b20f70cd22fc96ee3997db1492f536bbad0315"
  pullPolicy: Always
  registry: docker.io/mukhiddinov/user-service
containerPort: 8088
service:
  type: ClusterIP
  port: 8088
env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgres.db.svc.cluster.local:5432/agrodb
  - name: SPRING_DATASOURCE_USERNAME
    value: agro
  - name: SPRING_DATASOURCE_PASSWORD
    value: agro123
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: redpanda.kafka.svc.cluster.local:9093
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
