replicaCount: 1
nameOverride: ""
fullnameOverride: ""
image:
  repository: docker.io/mukhiddinov/shipping-service
  tag: "f13c702d305163a7730ec2a1b827325fe4bdf2f5"
  pullPolicy: Always
  registry: docker.io/mukhiddinov/shipping-service
containerPort: 8089
service:
  type: ClusterIP
  port: 8089
env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgres.db.svc.cluster.local:5432/agrodb
  - name: SPRING_DATASOURCE_USERNAME
    value: agro
  - name: SPRING_DATASOURCE_PASSWORD
    value: agro123
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: redpanda.kafka.svc.cluster.local:9093
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
