replicaCount: 1
nameOverride: ""
fullnameOverride: ""
image:
  registry: docker.io/mukhiddinov/catalog-service
  tag: "0af3b1048dbb6c948df4a2fdb9286efc54635481"
  repository: docker.io/mukhiddinov/catalog-service
containerPort: 8083
service:
  type: ClusterIP
  port: 8083
env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://postgres.db.svc.cluster.local:5432/agrodb
  - name: SPRING_DATASOURCE_USERNAME
    value: agro
  - name: SPRING_DATASOURCE_PASSWORD
    value: agro123
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: redpanda.kafka.svc.cluster.local:9093
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
