name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - account-service
          - cart-service
          - catalog-service
          - checkout-service
          - inventory-service
          - order-service
          - payment-service
          - pricing-service
          - shipping-service
          - user-service

    env:
      REGISTRY: docker.io
      IMAGE_NAMESPACE: mukhiddinov
      IMAGE_PREFIX: agro

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - run: mvn -pl ${{ matrix.service }} -am -DskipTests package

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        run: |
          IMAGE_REPO=${REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_PREFIX}-${{ matrix.service }}
          IMAGE_TAG=${GITHUB_SHA}

          docker build \
            --build-arg SERVICE_NAME=${{ matrix.service }} \
            -t ${IMAGE_REPO}:${IMAGE_TAG} .

          docker push ${IMAGE_REPO}:${IMAGE_TAG}
